window.CONFIG = {
  situations: ["CORDA_SINGOLA_SVINCOLABILE","CORDA_SINGOLA_NON_SVINCOLABILE","CORDA_DOPPIA","MANCORRENTE"],
  calataTypes: ["ASCIUTTA","CASCATA"],
  baseTypes: ["ASCIUTTA","LAGHETTO","POZZA_TURBOLENTA"],
  victimStates: ["COSCIENTE","INCOSCIENTE","NON_COLLABORATIVA"],
  cordaMagazzinoStates: ["SUFFICIENTE","NON_SUFFICIENTE","NON_UTILIZZABILE"],
  answers: ["DIRETTO_SINGOLA","DIRETTO_DOPPIA","INDIRETTO_SINGOLA","INDIRETTO_DOPPIA","PASSAGGIO_NODO","MINI_BILANCINO_MC","SVINCOLO_SOSTA","NESSUNA_MANOVRA"],
  timers: { FACILE: 15, MEDIO: 12, DIFFICILE: 10, DEFAULT: 12 },
  adminPin: "2468"
};